spring:
  data:
    mongodb:
      database: myfirstmongodb
      host: localhost
      port: 27017
      # username: myusername
      # password: mypassword
      # authentication-database: admin
      # ssl:
      #   enabled: true
      #   invalid-hostname-allowed: false
      #   key-store: classpath:keystore.p12
      #   key-store-password: keystorepassword
      #   key-store-type: PKCS12
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:~/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto=update: update
      generate-ddl: true