//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: FlightService.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializebookingResponse")
public inline fun bookingResponse(block: com.example.demo.grpc.BookingResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.BookingResponse =
  com.example.demo.grpc.BookingResponseKt.Dsl._create(com.example.demo.grpc.BookingResponse.newBuilder()).apply { block() }._build()
public object BookingResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.BookingResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.BookingResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.BookingResponse = _builder.build()

    /**
     * <code>bool success = 1;</code>
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * <code>bool success = 1;</code>
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * <code>string message = 2;</code>
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 2;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * <code>string bookingId = 3;</code>
     */
    public var bookingId: kotlin.String
      @JvmName("getBookingId")
      get() = _builder.getBookingId()
      @JvmName("setBookingId")
      set(value) {
        _builder.setBookingId(value)
      }
    /**
     * <code>string bookingId = 3;</code>
     */
    public fun clearBookingId() {
      _builder.clearBookingId()
    }

    /**
     * <code>string status = 4;</code>
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>string status = 4;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.BookingResponse.copy(block: com.example.demo.grpc.BookingResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.BookingResponse =
  com.example.demo.grpc.BookingResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

