//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: FlightService.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeflight")
public inline fun flight(block: com.example.demo.grpc.FlightKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.Flight =
  com.example.demo.grpc.FlightKt.Dsl._create(com.example.demo.grpc.Flight.newBuilder()).apply { block() }._build()
public object FlightKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.Flight.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.Flight.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.Flight = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string airline = 2;</code>
     */
    public var airline: kotlin.String
      @JvmName("getAirline")
      get() = _builder.getAirline()
      @JvmName("setAirline")
      set(value) {
        _builder.setAirline(value)
      }
    /**
     * <code>string airline = 2;</code>
     */
    public fun clearAirline() {
      _builder.clearAirline()
    }

    /**
     * <code>string origin = 3;</code>
     */
    public var origin: kotlin.String
      @JvmName("getOrigin")
      get() = _builder.getOrigin()
      @JvmName("setOrigin")
      set(value) {
        _builder.setOrigin(value)
      }
    /**
     * <code>string origin = 3;</code>
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }

    /**
     * <code>string destination = 4;</code>
     */
    public var destination: kotlin.String
      @JvmName("getDestination")
      get() = _builder.getDestination()
      @JvmName("setDestination")
      set(value) {
        _builder.setDestination(value)
      }
    /**
     * <code>string destination = 4;</code>
     */
    public fun clearDestination() {
      _builder.clearDestination()
    }

    /**
     * <code>string departureTime = 5;</code>
     */
    public var departureTime: kotlin.String
      @JvmName("getDepartureTime")
      get() = _builder.getDepartureTime()
      @JvmName("setDepartureTime")
      set(value) {
        _builder.setDepartureTime(value)
      }
    /**
     * <code>string departureTime = 5;</code>
     */
    public fun clearDepartureTime() {
      _builder.clearDepartureTime()
    }

    /**
     * <code>string arrivalTime = 6;</code>
     */
    public var arrivalTime: kotlin.String
      @JvmName("getArrivalTime")
      get() = _builder.getArrivalTime()
      @JvmName("setArrivalTime")
      set(value) {
        _builder.setArrivalTime(value)
      }
    /**
     * <code>string arrivalTime = 6;</code>
     */
    public fun clearArrivalTime() {
      _builder.clearArrivalTime()
    }

    /**
     * <code>double price = 7;</code>
     */
    public var price: kotlin.Double
      @JvmName("getPrice")
      get() = _builder.getPrice()
      @JvmName("setPrice")
      set(value) {
        _builder.setPrice(value)
      }
    /**
     * <code>double price = 7;</code>
     */
    public fun clearPrice() {
      _builder.clearPrice()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.Flight.copy(block: com.example.demo.grpc.FlightKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.Flight =
  com.example.demo.grpc.FlightKt.Dsl._create(this.toBuilder()).apply { block() }._build()

