//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: UserService.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializegetUserRequest")
public inline fun getUserRequest(block: com.example.demo.grpc.GetUserRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.GetUserRequest =
  com.example.demo.grpc.GetUserRequestKt.Dsl._create(com.example.demo.grpc.GetUserRequest.newBuilder()).apply { block() }._build()
public object GetUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.GetUserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.GetUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.GetUserRequest = _builder.build()

    /**
     * <code>string userId = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string userId = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.GetUserRequest.copy(block: com.example.demo.grpc.GetUserRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.GetUserRequest =
  com.example.demo.grpc.GetUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

