//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeoperationResponse")
public inline fun operationResponse(block: com.example.demo.grpc.OperationResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.OperationResponse =
  com.example.demo.grpc.OperationResponseKt.Dsl._create(com.example.demo.grpc.OperationResponse.newBuilder()).apply { block() }._build()
public object OperationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.OperationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.OperationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.OperationResponse = _builder.build()

    /**
     * <code>double result = 1;</code>
     */
    public var result: kotlin.Double
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>double result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.OperationResponse.copy(block: com.example.demo.grpc.OperationResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.OperationResponse =
  com.example.demo.grpc.OperationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

