//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeoperationRequest")
public inline fun operationRequest(block: com.example.demo.grpc.OperationRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.OperationRequest =
  com.example.demo.grpc.OperationRequestKt.Dsl._create(com.example.demo.grpc.OperationRequest.newBuilder()).apply { block() }._build()
public object OperationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.OperationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.OperationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.OperationRequest = _builder.build()

    /**
     * <code>double x = 1;</code>
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>double x = 1;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>double y = 2;</code>
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>double y = 2;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.OperationRequest.copy(block: com.example.demo.grpc.OperationRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.OperationRequest =
  com.example.demo.grpc.OperationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

