//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeprimeNumberResponse")
public inline fun primeNumberResponse(block: com.example.demo.grpc.PrimeNumberResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.PrimeNumberResponse =
  com.example.demo.grpc.PrimeNumberResponseKt.Dsl._create(com.example.demo.grpc.PrimeNumberResponse.newBuilder()).apply { block() }._build()
public object PrimeNumberResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.PrimeNumberResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.PrimeNumberResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.PrimeNumberResponse = _builder.build()

    /**
     * <code>int32 prime = 1;</code>
     */
    public var prime: kotlin.Int
      @JvmName("getPrime")
      get() = _builder.getPrime()
      @JvmName("setPrime")
      set(value) {
        _builder.setPrime(value)
      }
    /**
     * <code>int32 prime = 1;</code>
     */
    public fun clearPrime() {
      _builder.clearPrime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.PrimeNumberResponse.copy(block: com.example.demo.grpc.PrimeNumberResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.PrimeNumberResponse =
  com.example.demo.grpc.PrimeNumberResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

