//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeprimeNumberRequest")
public inline fun primeNumberRequest(block: com.example.demo.grpc.PrimeNumberRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.PrimeNumberRequest =
  com.example.demo.grpc.PrimeNumberRequestKt.Dsl._create(com.example.demo.grpc.PrimeNumberRequest.newBuilder()).apply { block() }._build()
public object PrimeNumberRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.PrimeNumberRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.PrimeNumberRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.PrimeNumberRequest = _builder.build()

    /**
     * <code>int32 number = 1;</code>
     */
    public var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>int32 number = 1;</code>
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.PrimeNumberRequest.copy(block: com.example.demo.grpc.PrimeNumberRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.PrimeNumberRequest =
  com.example.demo.grpc.PrimeNumberRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

