//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: FlightService.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializesearchRequest")
public inline fun searchRequest(block: com.example.demo.grpc.SearchRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.SearchRequest =
  com.example.demo.grpc.SearchRequestKt.Dsl._create(com.example.demo.grpc.SearchRequest.newBuilder()).apply { block() }._build()
public object SearchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.SearchRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.SearchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.SearchRequest = _builder.build()

    /**
     * <code>string origin = 1;</code>
     */
    public var origin: kotlin.String
      @JvmName("getOrigin")
      get() = _builder.getOrigin()
      @JvmName("setOrigin")
      set(value) {
        _builder.setOrigin(value)
      }
    /**
     * <code>string origin = 1;</code>
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }

    /**
     * <code>string destination = 2;</code>
     */
    public var destination: kotlin.String
      @JvmName("getDestination")
      get() = _builder.getDestination()
      @JvmName("setDestination")
      set(value) {
        _builder.setDestination(value)
      }
    /**
     * <code>string destination = 2;</code>
     */
    public fun clearDestination() {
      _builder.clearDestination()
    }

    /**
     * <code>string date = 3;</code>
     */
    public var date: kotlin.String
      @JvmName("getDate")
      get() = _builder.getDate()
      @JvmName("setDate")
      set(value) {
        _builder.setDate(value)
      }
    /**
     * <code>string date = 3;</code>
     */
    public fun clearDate() {
      _builder.clearDate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.SearchRequest.copy(block: com.example.demo.grpc.SearchRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.SearchRequest =
  com.example.demo.grpc.SearchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

