//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: UserService.proto

package com.example.demo.grpc;

@kotlin.jvm.JvmName("-initializeupdateUserRequest")
public inline fun updateUserRequest(block: com.example.demo.grpc.UpdateUserRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.UpdateUserRequest =
  com.example.demo.grpc.UpdateUserRequestKt.Dsl._create(com.example.demo.grpc.UpdateUserRequest.newBuilder()).apply { block() }._build()
public object UpdateUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.demo.grpc.UpdateUserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.UpdateUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.UpdateUserRequest = _builder.build()

    /**
     * <code>string userId = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string userId = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string name = 2;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string email = 3;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 3;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.demo.grpc.UpdateUserRequest.copy(block: com.example.demo.grpc.UpdateUserRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.UpdateUserRequest =
  com.example.demo.grpc.UpdateUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

